Repository CnCNet/xna-cncnet-client, pull requests merged in 2020-09, with the labels that each got.

#169 Implement blocking users from PM window
  DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
  DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
  DXMainClient/Online/CnCNetUserData.cs
Labels: enhancement

#163 Rework tunnel handling and add ping indication
  ClientCore/ProgramConstants.cs
  DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetGameLoadingLobby.cs
  DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
  DXMainClient/DXGUI/Multiplayer/CnCNet/TunnelListBox.cs
  DXMainClient/DXGUI/Multiplayer/CnCNet/TunnelSelectionWindow.cs
  DXMainClient/DXGUI/Multiplayer/GameLoadingLobbyBase.cs
  DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
  DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
  DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
  DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
  DXMainClient/Domain/Multiplayer/CnCNet/CnCNetTunnel.cs
  DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs
  DXMainClient/Domain/Multiplayer/LAN/LANPlayerInfo.cs
  DXMainClient/Domain/Multiplayer/PlayerInfo.cs
  DXMainClient/Resources/DTA/ping0.png
  DXMainClient/Resources/DTA/ping1.png
  DXMainClient/Resources/DTA/ping2.png
  DXMainClient/Resources/DTA/ping3.png
  DXMainClient/Resources/DTA/ping4.png
Labels: enhancement, feature, fix

#161 Implement game filter text box
  DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
  DXMainClient/DXGUI/Multiplayer/GameListBox.cs
  DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
  DXMainClient/DXGUI/Multiplayer/LANLobby.cs
Labels: feature
